version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - copyloopvar
    - decorder
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocritic
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - prealloc
    - promlinter
    - revive
    - staticcheck
    - tagalign
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
  settings:
    dupl:
      threshold: 400
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
      ignore-enum-types: ResourceName|Atom
    importas:
      alias:
        - pkg: k8s\.io/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s\.io/apimachinery/pkg/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: kerrors
        - pkg: k8s.io/apimachinery/pkg/apis/meta/internalversion
          alias: metainternalversion
      no-unaliased: true
    tagalign:
      order:
        - json
        - yaml
        - xml
        - form
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
