apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: controller
  newName: ghcr.io/loft-sh/cluster-api-provider-vcluster
  newTag: main
