apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  kubernetesVersion: "${KUBERNETES_VERSION:=}"
  kubernetesImage: "${KUBERNETES_IMAGE:=null}"  
  virtualClusterVersion: "${VCLUSTER_VERSION:=}"
  helmRelease:
    values: "${HELM_VALUES:=}"
    chart: 
      name: ${CHART_NAME:=null}
      repo: ${CHART_REPO:=null}
  controlPlaneEndpoint:
    host: ${VCLUSTER_HOST:=""}
    port: ${VCLUSTER_PORT:=0}
