apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: VCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: VCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  helmRelease:
    values: "${VCLUSTER_YAML:=}"
    chart: 
      name: ${CHART_NAME:=vcluster}
      repo: ${CHART_REPO:=https://charts.loft.sh}
      version: ${CHART_VERSION:=""}
