apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  helmRelease:
    values: "${VCLUSTER_YAML:=}"
    chart: 
      name: ${CHART_NAME:=vcluster}
      repo: ${CHART_REPO:=https://charts.loft.sh}
      version: ${CHART_VERSION:=""}
  controlPlaneEndpoint:
    host: ${VCLUSTER_HOST:=""}
    port: ${VCLUSTER_PORT:=0}
